export const businessPlans = [
  {
    name: "Paw Start",
    price: 0,
    branches: 1,
    monthlyStays: 10,
    description: "ลองจัดการร้าน เริ่มได้ฟรี",
    icon: "start",
    features: ["ข้อมูลสัตว์ การจอง และห้องพัก", "Daily Care 3 รายการ / การเข้าพัก", "รูป 5 รูป / การเข้าพัก", "ดู Pet Passport ที่เจ้าของแชร์"],
    action: "เริ่มต้นใช้งานฟรี",
  },
  {
    name: "Paw Care",
    price: 490,
    branches: 1,
    monthlyStays: null,
    description: "ดูแลร้านเต็มรูปแบบใน 1 สาขา",
    icon: "care",
    features: ["Daily Care และรูปภาพ", "เพิ่มพนักงานได้ไม่จำกัด", "ใส่โลโก้และชื่อร้าน", "ส่งออกข้อมูล (Export)"],
    action: "เริ่มต้นกับ Paw Care",
  },
  {
    name: "Paw Grow",
    price: 1490,
    branches: 10,
    monthlyStays: null,
    description: "รวมทุกสาขา ดูภาพรวมร้านในที่เดียว",
    icon: "grow",
    features: ["ทุกอย่างใน Paw Care", "พนักงานและการจองไม่จำกัด", "รายงานรวมและแยกตามสาขา", "จัดกลุ่มลูกค้าและดูประวัติ"],
    action: "เริ่มต้นกับ Paw Grow",
  },
] as const;

export const planComparisons = [
  { feature: "จำนวนสาขา", values: businessPlans.map((plan) => `${plan.branches} สาขา`) },
  { feature: "การเข้าพัก", values: businessPlans.map((plan) => plan.monthlyStays === null ? "ไม่จำกัด" : `${plan.monthlyStays} ครั้ง / เดือน`) },
  { feature: "ข้อมูลสัตว์", values: [true, true, true] },
  { feature: "การจอง", values: [true, true, true] },
  { feature: "ห้องพัก", values: [true, true, true] },
  { feature: "Daily Care (บันทึกการดูแล)", values: ["3 รายการ / การเข้าพัก", true, true] },
  { feature: "รูปภาพ", values: ["5 รูป / การเข้าพัก", true, true] },
  { feature: "Pet Passport", values: [true, true, true] },
  { feature: "พนักงานหลายคน", values: [false, "ไม่จำกัด", "ไม่จำกัด"] },
  { feature: "Branding ร้าน (โลโก้และชื่อร้าน)", values: [false, true, true] },
  { feature: "Export (ส่งออกข้อมูล)", values: [false, true, true] },
  { feature: "สแกน QR เพื่อเช็กอิน", values: [false, true, true] },
  { feature: "รายงานรวมและแยกตามสาขา", values: [false, false, true] },
  { feature: "จัดกลุ่มลูกค้าและดูประวัติ", values: [false, false, true] },
] as const;
